# Default values for monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    pullPolicy: IfNotPresent
  configMapNameOverride: {}
  revisionHistoryLimit: 1

nameOverride: ''
fullnameOverride: ''

prometheus:
  enabled: true

statsd:
  enabled: true
  serviceName: statsd
  log_level: info
  image:
    name: prom/statsd-exporter
    tag: v0.17.0
    sha:

resolution: 5m

c2cwsgiutils:
  enabled: true
  slowSqlSeconds: 10
  slowFetchSeconds: 20
  slowRouteSeconds: 90

print:
  enabled: false
  maxWaitSeconds: 10

apache:
  enabled: false

elasticsearch:
  enabled: false
  logTimeout: 120 # seconds before which a log must appear on ElasticSearch
  maxAge: 15 # minutes
  env: {}

namespaceGlobal:
  enabled: false
  project:
    resolution: 2m
  disk:
    warning: 90
    error: 92

kubernetes:
  containers:
    maxMemUsagePercent: 90
    maxCpuUsagePercent: 200
    maxReadyTime: 5m
  charts:
    - c2cgeoportal
    - monitoring
    - cache
    - redis
  ignoredPods:
    - dbstats
    - cron

processOoms:
  enabled: true
  serviceName: ooms
  image:
    name: camptocamp/es-ooms-exporter
    tag: latest
    sha:
  env: {}

dbstats:
  enabled: true
  serviceName: dbstats
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  backoffLimit: 0
  image:
    repository: camptocamp/c2cwsgiutils
    tag: latest
    sha:
  env: {}
  # LOG_LEVEL
  # PROMETHEUS_URL: http://prometheus-pushgateway.gs-metrics.svc:9091/
  # STATSD_URL
  annotations: {}
  resources: {}
  prometheus: true
  dbs: []
  # database: name # default to PGDATABASE environment variable
  # user: username # default to PGUSER environment variable
  # password: password # default to PGPASSWORD environment variable
  # host: hostname # default to PGHOST environment variable
  # port: port # default to PGPORT environment variable
  # schema: [schema1, schema2]

cache:
  enabled: false

postgresql:
  enabled: false
  hosts:
    master:
      # A secret with password, username, hostname, hostnameSlave, database
      secret: secrets-postgresql-prod
      addressKey: hostname
    slave:
      secret: secrets-postgresql-prod
      addressKey: hostnameSlave
    master-12:
      secret: secrets-postgresql-prod-12
      addressKey: hostname
    slave-12:
      secret: secrets-postgresql-prod-12
      addressKey: hostnameSlave
  connections:
    warning: 0.80
    error: 0.90
  replication:
    period: 10m
    maxLag: '10'
  image:
    repository: wrouesnel/postgres_exporter
    tag: v0.8.0

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: default

nodeSelector: {}

tolerations: []

affinity: {}
