---
# Default values for monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ''
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent

statsd:
  enabled: true
  log_level: info
  image:
    name: prom/statsd-exporter
    tag: v0.17.0

resolution: 5m

c2cwsgiutils:
  enabled: true
  slowSqlSeconds: 10
  slowFetchSeconds: 20
  slowRouteSeconds: 90

print:
  enabled: false
  maxWaitSeconds: 10

apache:
  enabled: false

elasticsearch:
  enabled: false
  logTimeout: 120 # seconds before which a log must appear on ElasticSearch
  maxAge: 15 # minutes
  env: {}

global:
  enabled: false
  project:
    resolution: 2m
  disk:
    warning: 90
    error: 92

kubernetes:
  containers:
    maxMemUsagePercent: 90
    maxCpuUsagePercent: 200
    maxReadyTime: 5m
  charts:
    - c2cgeoportal
    - monitoring
    - cache
    - redis
  ignoredPods:
    - dbstats
    - cron

processOoms:
  enabled: true
  serviceName: ooms
  image:
    name: camptocamp/es-ooms-exporter
    tag: latest
  env: {}

cache:
  enabled: true

postgresql:
  enabled: false
  hosts:
    master:
      # A secret with password, username, hostname, hostnameSlave, database
      secret: secrets-postgresql-prod
      addressKey: hostname
    slave:
      secret: secrets-postgresql-prod
      addressKey: hostnameSlave
    master-12:
      secret: secrets-postgresql-prod-12
      addressKey: hostname
    slave-12:
      secret: secrets-postgresql-prod-12
      addressKey: hostnameSlave
  connections:
    warning: 0.80
    error: 0.90
  replication:
    period: 10m
    maxLag: '10'
  image:
    repository: wrouesnel/postgres_exporter
    tag: v0.8.0

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: default

nodeSelector: {}

tolerations: []

affinity: {}

revisionHistoryLimit: 1
