# Default values for monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    pullPolicy: IfNotPresent
  configMapNameOverride: {}
  revisionHistoryLimit: 1

nameOverride: ''
fullnameOverride: ''

prometheus:
  enabled: true

statsd:
  enabled: false
  serviceName: statsd
  log_level: info
  image:
    name: prom/statsd-exporter
    tag: v0.17.0
    sha:

resolution: 5m

c2cwsgiutils:
  enabled: true
  slowSqlSeconds: 10
  slowFetchSeconds: 20
  slowRouteSeconds: 90

print:
  enabled: false
  maxWaitSeconds: 10

kubernetes:
  containers:
    maxMemUsagePercent: 90
    maxCpuUsagePercent: 200
    maxReadyTime: 5m
  charts:
    - c2cgeoportal
    - monitoring
    - cache
    - redis
  ignoredPods:
    - dbstats
    - cron

processOoms:
  enabled: true
  serviceName: ooms
  image:
    name: camptocamp/es-ooms-exporter
    tag: latest
    sha:
  env: {}

dbstats:
  enabled: true
  serviceName: dbstats
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  backoffLimit: 0

  image:
    repository: camptocamp/c2cwsgiutils
    tag: latest
    sha:

  # By default we use Prometheus pull model, but we can use pushgateway
  prometheusPushgateway:
    enabled: false

  env:
    C2C_PROMETHEUS_PORT:
      value: '9090'
  # LOG_LEVEL

  annotations: {}
  resources: {}
  dbs: []
  # database: name # default to PGDATABASE environment variable
  # user: username # default to PGUSER environment variable
  # password: password # default to PGPASSWORD environment variable
  # host: hostname # default to PGHOST environment variable
  # port: port # default to PGPORT environment variable
  # schema: [schema1, schema2]

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: default

nodeSelector: {}

tolerations: []

affinity: {}
