{{- if .Values.dbstats.enabled }}
{{- $config := dict "root" . "service" .Values.dbstats -}}
{{- if semverCompare ">=1.21.0" ( trimPrefix "v" $.Capabilities.KubeVersion.Version ) }}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "common.fullname" $config }}
  {{- include "common.metadata" $config | nindent 2 }}
spec:
  schedule: "{{ mod (regexReplaceAll "[a-f]+" (printf "%s-%s" .Release.Namespace .Release.Name | sha256sum) "" | trunc 5) 60 }} * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata: {{ include "common.podMetadata" $config | nindent 10 }}
        spec: {{ include "common.podConfig" $config | nindent 10 }}
          restartPolicy: Never
          containers:
            - name: dbstats
              {{- include "common.containerConfig" ( dict "root" . "container" .Values.dbstats ) | nindent 14 }}
              args:
                - bash
                - -cxe
                - |
                  {{- range .Values.dbstats.dbs  }}
                  {{- if $.Values.dbstats.prometheus }}
                  TARGET="--prometheus_instance={{ $.Release.Namespace }}-{{ template "common.fullname" ( dict "root" $ "service" $.Values ) }}-{{ .database | default "$(PGDATABASE)" }} --prometheus_url=${PROMETHEUS_URL}"
                  {{- else }}
                  TARGET="--statsd_address=${STATSD_URL} --statsd_prefix=dbstats"
                  {{- end }}
                  export STATSD_TAG_DB="{{ .database | default "$(PGDATABASE)" }}"
                  c2cwsgiutils-stats-db \
                    --db=postgresql://{{ .user | default "$(PGUSER)" }}:{{ .password | default "$(PGPASSWORD)" }}@{{ .host | default "$(PGHOST)" }}:{{ .port | default "$(PGPORT)" }}/{{ .database | default "$(PGDATABASE)" }} \
                    {{- range .schemas }}
                    --schema={{ . }} \
                    {{- end }}
                    ${TARGET}
                  {{- end }}
{{- end }}
