{{- if .Values.processOoms.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.processOoms ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.processOoms ) | nindent 4 }}
  annotations: {{- toYaml .Values.processOoms.annotations | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" . "service" .Values.processOoms ) | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.selectorLabels" ( dict "root" . "service" .Values.processOoms ) | nindent 8 }}
    spec: {{- include "common.podConfig" ( dict
          "root" .
          "service" .Values.processOoms
          "affinitySelector" (dict
            "app.kubernetes.io/instance" .Release.Name
            "app.kubernetes.io/name" ( include "common.name" ( dict "root" . "service" .Values.processOoms ) )
            "app.kubernetes.io/component" "main"
          )) | nindent 6 }}
      containers:
        - name: process-ooms
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.processOoms ) | nindent 10 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          securityContext:
            runAsNonRoot: true
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
{{- end }}
