{{- if .Values.processOoms.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.processOoms ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.processOoms ) | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.processOoms ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.processOoms ) | nindent 4 }}
rules:
  - apiGroups: ["apps/v1"]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: ["v1"]
    resources: ["ns"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.processOoms ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.processOoms ) | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "common.fullname" ( dict "root" . "service" .Values.processOoms ) }}
roleRef:
  kind: Role
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.processOoms ) }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
