{{- if .Values.process_ooms.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "monitoring.fullname" . }}-process-ooms
  labels:
    app: {{ template "monitoring.fullname" . }}
    chart: {{ template "monitoring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: process-ooms
    prometheus: "true"
spec:
  type: ClusterIP
  ports:
    - port: 9102
      targetPort: http
      protocol: TCP
      name: prometheus
  selector:
    app: {{ template "monitoring.fullname" . }}
    release: {{ .Release.Name }}
    service: process-ooms
{{- end }}
