{{- if .Values.process_ooms.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "monitoring.fullname" . }}-process-ooms
  labels:
    app: {{ template "monitoring.fullname" . }}
    chart: {{ template "monitoring.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "monitoring.fullname" . }}-process-ooms
  labels:
    app: {{ template "monitoring.fullname" . }}
    chart: {{ template "monitoring.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: ["project.openshift.io"]
    resources: ["projects"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "monitoring.fullname" . }}-process-ooms
  labels:
    app: {{ template "monitoring.fullname" . }}
    chart: {{ template "monitoring.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
subjects:
  - kind: ServiceAccount
    name: {{ template "monitoring.fullname" . }}-process-ooms
roleRef:
  kind: Role
  name: {{ template "monitoring.fullname" . }}-process-ooms
{{- end }}