{{- if .Values.processOoms.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.processOoms ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.processOoms ) | nindent 4 }}
    prometheus: "true"
spec:
  type: ClusterIP
  ports:
    - port: 9102
      targetPort: http
      protocol: TCP
      name: prometheus
  selector: {{- include "common.selectorLabels" ( dict "root" . "service" .Values.processOoms ) | nindent 4 }}
{{- end }}
