{{- define "rules" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "common.fullname" ( dict "root" .root "service" .root.Values ) }}
  labels: {{ include "common.labels" ( dict "root" .root "service" .root.Values ) | nindent 4 }}
    prometheus: example
    role: alert-rules
spec:
{{ tpl (.root.Files.Get ( print "prometheus_rules/" .name ".rules")) .root | indent 2 }}
{{- end -}}

{{- if .Values.c2cwsgiutils.enabled }}
{{-   template "rules" (dict "name" "c2cwsgiutils" "root" .) }}
{{- end }}

{{- if .Values.print.enabled }}
{{-   template "rules" (dict "name" "mapfish-print" "root" .) }}
{{- end}}
