apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values ) | nindent 4 }}
spec:
  selector:
    matchLabels:
      prometheus: "true"
  endpoints:
    - port: prometheus
      interval: 10s
      honorLabels: true
