{{- if .Values.statsd.enabled }}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.statsd ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.statsd ) | nindent 4 }}
  annotations: {{- toYaml .Values.statsd.annotations | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" . "service" .Values.statsd ) | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.selectorLabels" ( dict "root" . "service" .Values.statsd ) | nindent 8 }}
    spec: {{- include "common.podConfig" ( dict "root" . "service" .Values.statsd "affinitySelector" (dict "app.kubernetes.io/instance" .Release.Name "app.kubernetes.io/name" ( include "common.name" ( dict "root" . "service" .Values.statsd ) ) "app.kubernetes.io/component" "main" )) | nindent 6 }}
      volumes:
        - name: mappings-volume
          configMap:
            name: {{ include "common.fullname" ( dict "root" . "service" .Values.statsd ) }}
      containers:
        - name: statd
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.statsd ) | nindent 10 }}
          args:
            - --statsd.mapping-config=/etc/statsd/mappings.yaml
            - --log.level={{ .Values.statsd.log_level }}
            - --statsd.listen-tcp=
          volumeMounts:
            - mountPath: /etc/statsd
              name: mappings-volume
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: http
              containerPort: 9102
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
{{- end }}
