{{- if .Values.statsd.enabled }}
{{- $config := dict "root" . "service" .Values.statsd -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" $config }}
  {{- include "common.metadata" $config | nindent 2 }}
spec:
  replicas: {{ .Values.statsd.replicaCount | default 1}}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit | default 0 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: {{- include "common.selectorLabels" $config | nindent 6 }}
  template:
    metadata: {{- include "common.podMetadata" $config | nindent 6 }}
    spec: {{- include "common.podConfig" ( dict "root" . "service" .Values.statsd "affinitySelector" (dict "app.kubernetes.io/instance" .Release.Name "app.kubernetes.io/name" ( include "common.name" $config ) "app.kubernetes.io/component" "main" )) | nindent 6 }}
      volumes:
        - name: mappings-volume
          configMap:
            name: {{ include "common.fullname" $config }}
      containers:
        - name: statd
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.statsd ) | nindent 10 }}
          args:
            - --statsd.mapping-config=/etc/statsd/mappings.yaml
            - --log.level={{ .Values.statsd.log_level }}
            - --statsd.listen-tcp=
          volumeMounts:
            - mountPath: /etc/statsd
              name: mappings-volume
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: http
              containerPort: 9102
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
{{- end }}
