{{- if .Values.statsd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.statsd ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.statsd ) | nindent 4 }}
data:
  mappings.yaml: |
{{ tpl (.Files.Get "configs/mappings.yaml") . | indent 4 }}
{{- end }}
